### ISSUE TITLE
Timeline hangs without errors: spinning wheel loops

### ISSUE THREAD

**Issue by iwkse** [taigaio/taiga-back#1086]
I've installed on my own server the latest Taiga sources.
The timeline never shows the information but keep spinning.
I don't see any errors on dev tools, please could you provide debugging info to try to spot the issue?

**Comment by migonzalvar** [comment]
Hi @iwkse.

I'm not sure what the problem is but it seems the request it's not reaching the Django server.

If you could describe your setup  and send an email to taiga mailing list in https://groups.google.com/d/forum/taigaio I'm pretty sure someone could help you.

In any case I think it's not an issue related with taiga-back source code.

**Comment by iwkse** [comment]
Hi @migonzalvar, thanks for the link. Seems like a permission issue though. If you're interested I've just followed an existing similar thread, https://groups.google.com/forum/#!searchin/taigaio/timeline%7Csort:date/taigaio/3abc-nVDPdY/SpkqKbNuAwAJ
