### ISSUE TITLE
Email invite link invalid

### ISSUE THREAD

**Issue by callahan22** [taigaio/taiga-back#1094]
Hi,

I have a working install of Taiga up and running on my own hosted solution. There's one remaining issue that I can't seem to solve.
I've disabled public registrations to prevent anyone from registering on the site when they land on it. The plan is that the few users that I've manually set up on there can then control the platform and invite who they like to the Taiga instance. However, when existing users send invites to potential new users, the email arrives in their inbox but the link to accept the invitation is missing the hostname so the link ends up looking like: example.com/invitation/f98aaa8e-426b-11e8-9a99-0050568d0b9b.

I can't find where in the config I need to make an adjustment to make the invite link valid. Can someone point me at that I need to change to make this work?

Secondly, if possible I would like to change the wording in the invite. Again, I've not been able to locate the file I need to update to change this. If anyone can point me in the right direction, I'd appreciate it.

Thanks for your help.

**Comment by bameda** [comment]
The url is because you [settings](https://taigaio.github.io/taiga-doc/dist/setup-production.html#_backend_configuration) in `taiga-back/settings/local.py` is wrong, change:
```
SITES["front"]["scheme"] = "http"
SITES["front"]["domain"] = "example.com"
```
with the correct values and restart the server.

Invitation emails is at 
```
taiga-back/taiga/projects/templates/emails/membership_invitation-body-html.jinja
taiga-back/taiga/projects/templates/emails/membership_invitation-body-text.jinja
taiga-back/taiga/projects/templates/emails/membership_invitation-subject.jinja
```
But if you change this is probably that you show regenerate locales (at `taiga-back/taiga/locale/*`) for every language. There is more info about [how to regenerate django locales files](https://docs.djangoproject.com/en/2.0/topics/i18n/translation/#localization-how-to-create-language-files).

Regards
