### ISSUE TITLE
Github integration not available

### ISSUE THREAD

**Issue by Seluj78** [taigaio/taiga-back#1137]
**Do you want to request a *feature* or report a *bug*?**
Bug report

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/4641317/42018378-37e5161a-7ab2-11e8-8f98-d043d992b9c3.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
Create new project -> import
**What is the expected behavior?**
https://tree.taiga.io/support/importers/github-importer/
**Is it happening in taiga.io or in your own instance?**
Own instance
**What browser/version are you using?**
Firefox 60.0.2
**Are there any console errors *(Ctrl + F12)* in red?**
None

**Comment by douglascrp** [comment]
In order to see the importer listed in that page, you have to proceed as described at https://github.com/taigaio/taiga-doc/blob/master/setup-faqs.adoc#32-how-can-i-configure-github-importers-in-my-own-instance

So, basically, register the application, configure the taiga-back and restart it.
Then add the importer in the taiga-client, and restart the webserver service.

That is how I enabled Trello importer yesterday, and it worked just like described.

**Comment by Seluj78** [comment]
Oh perfect ! Thanks a lot for the info !

**Comment by Seluj78** [comment]
What callback url should I set tho ?

**Comment by douglascrp** [comment]
I don't know about any url.
There is no callback url mentioned in the link I sent to you before.

The next topic has a callback url, but that is only for Asana.

**Comment by Seluj78** [comment]
Yes got it, just set the base url as the callback. Now the thing is, the import worked the first time but now it fails and stops after 2 users. It doesnt import issues, says it failed and stops, the project is created empty

**Comment by Seluj78** [comment]
At first i thought it failed on only one project, but other projects fail too.

**Comment by douglascrp** [comment]
I hope someone else can answer about that, as what I used as the trello one, which worked perfectly.

**Comment by Seluj78** [comment]
I opened an issue for that

**Comment by Seluj78** [comment]
My bad fail
