### ISSUE TITLE
cairocffi 1.2.0 doesn't support EOL Python 3.5

### ISSUE THREAD

**Issue by antgel** [taigaio/taiga-back#1522]
I found this when trying to upgrade to latest stable on Ubuntu 16.04. See https://github.com/Kozea/cairocffi/commit/c93eb812ab54ab6666cbeb1c8eb64934c3cc4544 - cairocffi 1.2.0 no longer supports Python 3.5, which is EOL anyway. This makes the install docs out of date. I guess I'll try upgrading to 18.04 LTS.

**Comment by Wazabiii** [comment]
Thanks @antgel for the lead.

After upgrading from Ubuntu 16.04 to 18.04, (`sudo do-release-upgrade`) 
I've python 3.6 by default.

But the taiga virtualenv still running on python 3.5.
To update the virtualenv from python 3.5 to 3.6, run:
```
cd ~/taiga-back/
mkvirtualenv -p /usr/bin/python3 taiga
```
```
workon taiga
```

```
python --version
Python 3.6.9
```
Continue the update process following: http://taigaio.github.io/taiga-doc/dist/upgrades.html
```
pip install -r requirements.txt
python manage.py migrate --noinput
python manage.py compilemessages
python manage.py collectstatic --noinput
```

Due to the invalid python 3.5 version on ubuntu 18.04, we should restart taiga after the upgrade (in my case):

```
systemctl restart taiga
```
