### ISSUE TITLE
Circus and python 3.4

### ISSUE THREAD

**Issue by psgganesh** [taigaio/taiga-back#251]
Accodring to this link https://circus.readthedocs.org/en/0.9.2/installation/#more-on-requirements
Circus can only be used until python 2.7, but taiga uses python 3.4, am unable to get this to work....

**Comment by niwibe** [comment]
Circus is an independent application than manages system processes. It can be written in any language, an in that case: python2. 

If yo can not get taiga work, surelly is not because circus is written with python2.

Can you write to the taiga mailing list and explain your problem with more details?

**Comment by psgganesh** [comment]
Sure will keep you folks posted, thank you for the response...

**Comment by psgganesh** [comment]
Circus is working with python

**Comment by superalex** [comment]
Great!
