### ISSUE TITLE
Allow modification of strings in email templates and elsewhere

### ISSUE THREAD

**Issue by tanc** [taigaio/taiga-back#254]
Is there a way of modifying all the stock strings on a self hosted instance? For instance, modifying the text in emails, or changing the empty description field text. It would be great to be able to customise these without making changes to core files in the repository.

**Comment by superalex** [comment]
Hello @tanc,

We have some open issues related to support i18n in taiga (in taiga-back and in taiga-front), we will have to wait some weeks before starting with it but it's in our roadmap. When i18n is fully supported you will be able of making those changes without touching core files, just the translation ones.

Regards,

**Comment by tanc** [comment]
Excellent, that's good news. I'd seen the Spanish translation file and guessed there would be an i18n way of doing string overrides. Thanks for your swift reply and thanks for the excellent work on this system so far. Looking forward to seeing the system mature.

**Comment by tanc** [comment]
Hi Alex, just checking in about this issue. I noticed that translations for German and Dutch are part of 1.8.0 so was wondering if its now possible to translate the email text?

**Comment by bameda** [comment]
Yes, you can help us:

1. Access to our team of translators with this link: https://www.transifex.com/organization/taiga-agile-llc/
2. Set up an account in Transifex
3. Start contributing.

**Comment by tanc** [comment]
My intention is not to translate Taiga into other languages, its simply to customise our self-hosted install with the messages we feel appropriate for our users. This support request was to ask how to do this and Alex had said that once i18n had landed properly there would be a way to do it without modifying any core files. Can you confirm this is now possible and how I go about doing it?

**Comment by bameda** [comment]
Sorry for the misunderstanding. The only way I can think to do this is editting the locales files in the clienta and in the server.

**Comment by tanc** [comment]
Thanks for re-opening. So I guess this is a feature request (enhancement) to allow some way of modifying strings on a self-hosted install.

**Comment by superalex** [comment]
Hello @tanc,

Actually you can fully customize your taiga translations (so the enhancement was done for me when we released the i8n support).

- For taiga-front you should customize your app/locales/locale-XX.json 
- For taiga-back just edit your taiga/locale/XX/LC_MESSAGES/django.po files and then execute "python manage.py compilemessages"

You should be careful when updating (git pull), because it will try to update these files, probably you should do a local commit before it and merge this files when updating.

I'm closing the issue again ;) (reopening if needed, of course)
