### ISSUE TITLE
[BUG] Bulk update backlog order return Status code 400 {"bulk_stories": ["This field is required."]}

### ISSUE THREAD

**Issue by MathieuSevegny** [taigaio/taiga-back#28]
When I drag a User Story from my backlog to a sprint, the api returns me a status code 400 with the following response : {"bulk_stories": ["This field is required."]}.
To workaround this, I have to check the User Story and press on "Move to Current Sprint".

To reproduce this error : 
1. Create a Scrum
2. Create a sprint inside it
3. Create a User Story in the backlog
4. Drag the User Story in the box "Drop here Stories from your backlog to start a new sprint"

I can still work but it slow me down a lot, I have to check the User Story and press on "Move to Current Sprint".

![bug](https://user-images.githubusercontent.com/55141786/123842112-6abc5980-d8de-11eb-9533-9b4fd97a6618.gif)

I use Taiga self hosted. I am on the stable version 6.2.1 for the back an the front.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: All
 - Version: Taiga version 6.2.1

**Comment by bameda** [comment]
Hi @MathieuSevegny 

this could be because you are using and old version of taiga-front or because you should clean your browser cache to use the last version. In the stable branches, we can't reproduce this error. Make sure you have compiled the latest version (or you have downloaded the latest taiga-front-dist) and your browser is using this recent code.

Best regards.
