### ISSUE TITLE
Support the ability to create organizations.

### ISSUE THREAD

**Issue by phpmypython** [taigaio/taiga-back#292]
It would be nice to have the ability to make a client and then upon making a project you can assign the projects to that client/organization. This would make it a lot easier to organize projects, this is a feature i loved in Redmine and it would be nice to see it here.

**Comment by superalex** [comment]
Thanks for the feedback!,

We have a user story in our backlog for this one, we were thinking in creating a system of teams/organizations similar to the github one or Trello. We have no exact date but I hope you can see it as a new feature soon :)

I', closing this one because we have another issue open for organizations -> https://github.com/taigaio/taiga-back/issues/87
