### ISSUE TITLE
[bug / enhancement] Sidebar too small for items

### ISSUE THREAD

**Issue by matanshukry** [taigaio/taiga-back#314]
After adding many modules, on my small screen laptop, it seems the icons overlap the account button.
In the following picture, you can see the account and the admin buttons are overlapping.

![image](https://cloud.githubusercontent.com/assets/5613042/7339155/ef7bd64c-ec6c-11e4-84d3-27ce6e9c8838.png)

Suggested fix:
 * Let the user change the icon size
 * Use some sort of scrolling

The second approach is probably the better one, at least in my opinion, since in time we might have more modules, which might make the sidebar crowded. That is, you don't want the space to limit the number of modules you use.

**Comment by Xaviju** [comment]
Hi @matanshukry thanks for the bug report.
Its a known bug for Taiga in small screens. This will be fixed in he next release, probably in a couple weeks from now. Icons will become smaller so more options can fit in the screen: https://github.com/taigaio/taiga-design/blob/master/layout/public-layout.svg
