### ISSUE TITLE
Mandrill as mailserver

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-back#320]
Would be nice to have an option for using Mandrill as mailserver.
And together with this easy to configure templates for the different mails / notifications.

**Comment by jespino** [comment]
Hi @florisvanwoudenberg, Thanks for your feedback :smiley: 

Taiga is, in the end, a django application, then, you can configure your settings/local.py to use any email backend supported by django, for example, you can use djrill (https://djrill.readthedocs.org/en/v1.3/installation/#configuration) to send emails through mandrill service, and mandrill service have standard smtp service, then you can configure it through the standard smtp setting of django, or using your own MTA to redirect the sendings to the mandrill SMTP.

If you want a more deep integration with mandrill, probably the best option is to open a new enhancement proposal explaining how you see this integration.

**Comment by s3m3n** [comment]
I have some issues using `djrill` with `taiga-back`. Everything is configured properly but djrill throws exception which in short indicates that `json.dumps(payload)` could not convert all EmailMessage fields into JSON which is required for Mandrill API request. I read that under [djrill issue](https://github.com/brack3t/Djrill/issues/100).

[Request log with exception](https://github.com/taigaio/taiga-back/files/134448/log.txt) (added some asterisks instead of real data).

As a python noob it would be nice to get some support so Taiga can really use power of Mandrill.

**Comment by s3m3n** [comment]
@jespino @superalex should I open this case as a new issue?

**Comment by superalex** [comment]
Hello @s3m3n @bameda is working on this issue we will let you know when we have more info about it!

**Comment by bameda** [comment]
Hi @s3m3n i test it and fix the problem here https://github.com/taigaio/taiga-back/commit/190fa3d6766648bbc5e2487c65ac519baa5fa3b7

You can upgrade your taiga-back repository now to fix it.
