### ISSUE TITLE
Scrum Master should be a default role

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-back#329]
In the default configuration of a (scrum) project, the role scrum master is not available. So this has to be added manually for each project. Is there a reason for not adding this role?
IMO this should be added to the scrum project template.

**Comment by superalex** [comment]
Hello @florisvanwoudenberg,

The reason is that we found most of our users/projects were not using it, so we decided not adding it by default. 

Actually the taiga API support templates for creating projects and we want it to the web app too. This way you could create your custom template for projects (with the roles, default permissions, custom fields...) that you need and use it for your new projects.

Regards!

**Comment by florisvanwoudenberg** [comment]
Ok, thanks @superalex
