### ISSUE TITLE
HTTP 500 for Creating new user

### ISSUE THREAD

**Issue by mehrad-rafigh** [taigaio/taiga-back#391]
Hey everybody,

I wanted to check out if we (our startup) can use taiga. So I installed Taiga via the taiga-script and everything is up and running. 
The only problem, that I have encountered is while creating a new user. Taiga throws the very nice Oompa Lompa message. When I open the Developer Tools in Chrome I can see that an HTTP 500 error is thrown. So to help you guys help me, which log files should I check in order to solve this problem. BTW I already checked Issue 244, but the Issue the fellow taiga user had, was an HTTP 502. 
Thanks in advance

**Comment by bameda** [comment]
Please @mehrad-rafigh for setup issues send us an email to our mailing list https://groups.google.com/forum/#!forum/taigaio

Backend logs are in ```/home/$USER/logs/```

**Comment by hamoid** [comment]
I successfully created 5 users. When I tried to create more, I was getting a 500 error. The reason, I think, is because e-mail is a key in the database, and it can not be duplicate. If I try to create users, with user name and password via the /admin/, the e-mails are empty by default, and it fails when adding the second user with no e-mail.

It would be nice if the interface asked for user name, password AND e-mail. Also, if the error was not just a "500", which forces to look into the logs, but something more meaningful. Cheers!
