### ISSUE TITLE
Ability to track user stories across sprints

### ISSUE THREAD

**Issue by brettp** [taigaio/taiga-back#438]
Currently there is no easy way to track a user story across sprints. For example, when a US isn't completed and needs to be carried on in the next sprint, you have to move the entire US. This changes the sprint's points and velocity.

A possible solution is a button on the US that copies it to a sprint. You could present a screen to select only specific tasks to copy.

**Comment by superalex** [comment]
Hello @brettp 

Best practices for scrum use to recommend that if you can't finish a user story in a sprint then you should move it completely to the following one. It will be reflected in the sprint velocity but it's a signal that something bad was happening: "was the us underestimated?", "something affected the speed"?, "did we have any block?". The idea is that visualizing the problem is the most important here.

About the copy feature, we had an existing enhancement request here -> https://tree.taiga.io/project/taiga/issue/2488. I'm adding your feedback there

Regards!,

**Comment by brettp** [comment]
@superalex I asked my scrum leader for more info on the use case for this. Here's her reply:

> What's missing is the insight from previous sprints into what you thought you could do and what you actually did. Using the practice of just moving them to the next sprint you have your velocities reflected correctly, but it looks like you "completed" each sprint successfully...which is not the case. Tracking issues that were moved to the next sprint can come in handy when doing reviews and retrospectives so you can say hey...what happened here, we only did 50% of what we expected.

**Comment by superalex** [comment]
I agree, it looks like a completed a sprint but it should be a really slow one so the impact in the burndown graph should be much more visual. We prefered to choose the approach of visualizing the problem immediately, the exact amount of work done can be calculated later.

Regards!,

**Comment by jumbojett** [comment]
+ 1

**Comment by lordloh** [comment]
`vote++`
I would like to see something like this too. I would like to keep points with respect to tasks instead of the user story. When I close a US after dragging it through 10 sprints, will that  10th sprint not have an extreme velocity?

I am new to scrum and sprint and my be saying something silly here.
