### ISSUE TITLE
DATE_URL not declared in taiga.projects.custom_attributes.choices

### ISSUE THREAD

**Issue by msampaio** [taigaio/taiga-back#616]
I tried to follow setup development envionment, described in README and got an error running `python manage.py sample_data`. The variable `DATE_URL` is not declared. The problem occurs here: https://github.com/taigaio/taiga-back/blob/master/taiga/projects/management/commands/sample_data.py#L288

I checked `custom_attributes` and didn't find `DATE_URL`.

**Comment by bameda** [comment]
Hi @msampaio I fix it here (https://github.com/taigaio/taiga-back/commit/7df6450fae3cb58213ed12be670afb2263d79b8c) but if you want to install Taiga don't use master branch because is the dev one and it's very unstable.

Follow the setup instructions from http://taigaio.github.io/taiga-doc/dist/ 

Regards
