### ISSUE TITLE
[Q] setup taiga_contrib_oidc_auth w/ keycloak  - (TaigaNext can ignore, maybe a fellow user will have the answer?)

### ISSUE THREAD

**Issue by lknite** [taigaio/taiga-back#66]
Hello, noticed the taiga_contrib_oidc_auth plugin looks like it will be more supported than community provided plugins so I am working to set up taiga6 to use it with keycloak.

I was able to follow the setup steps and believe I have everything setup correctly yet I'm getting a 404 when I click OPENID CONNECT.  I've looked through logs and am not seeing anything useful related to what I'm trying to do.

(Note, harmony.net in these config files is not a real publicly accessible domain.  This setup is all onprem.)

What are some troubleshooting steps I could perform?  I'm not sure what else to check.

/taiga-back/settings/local.py
```
from .common import *

# debug
f = open("/tmp/debug.log", "a")
f.write("processing: local.py\n")
f.close()

INSTALLED_APPS += [
    "mozilla_django_oidc",
    "taiga_contrib_oidc_auth",
]

AUTHENTICATION_BACKENDS = list(AUTHENTICATION_BACKENDS) + [
    "taiga_contrib_oidc_auth.oidc.TaigaOIDCAuthenticationBackend",
]

# Add the OIDC urls
ROOT_URLCONF = "settings.urls"

# OIDC Settings
OIDC_CALLBACK_CLASS = "taiga_contrib_oidc_auth.views.TaigaOIDCAuthenticationCallbackView"
OIDC_RP_SCOPES = "openid email profile"
OIDC_RP_SIGN_ALGO = "RS256"
#OIDC_RP_IDP_SIGN_KEY = ""
OIDC_VERIFY_SSL = False
# Set the OIDC provider here.
OIDC_BASE_URL = "https://keycloak.k-prod.harmony.net/auth/realms/harmony/protocol/openid-connect"
# Those URL values work for Ipsilon.
OIDC_OP_JWKS_ENDPOINT = OIDC_BASE_URL + "/certs"
OIDC_OP_AUTHORIZATION_ENDPOINT = OIDC_BASE_URL + "/auth"
OIDC_OP_TOKEN_ENDPOINT = OIDC_BASE_URL + "/token"
OIDC_OP_USER_ENDPOINT = OIDC_BASE_URL + "/userinfo"
# These two are private! Don't commit them to VCS. Getting the values from
# environment variables is a good way.
import os
OIDC_RP_CLIENT_ID = "taiga.k-dev.harmony.net" #os.getenv("OIDC_RP_CLIENT_ID")
OIDC_RP_CLIENT_SECRET = "hidden" #os.getenv("OIDC_RP_CLIENT_SECRET")
#OIDC_RP_CLIENT_ID = os.getenv("OIDC_RP_CLIENT_ID")
#OIDC_RP_CLIENT_SECRET = os.getenv("OIDC_RP_CLIENT_SECRET")
```

/taiga-back/settings/urls.py
```
from taiga.urls import *

# debug
f = open("/tmp/debug.log", "a")
f.write("processing: urls.py\n")
f.close()

urlpatterns += [
    url(r"^oidc/", include("mozilla_django_oidc.urls")),
]
```
![image](https://user-images.githubusercontent.com/92187614/147803560-bb2fad9b-21d8-4110-ab7a-312a56e3a916.png)
![image](https://user-images.githubusercontent.com/92187614/147803577-d4c825a7-cb4e-437f-a81c-5fdc5652e705.png)

**Comment by lknite** [comment]
Is the /taiga-back/settings/local.py no longer used?  Something else needed to get the local.py to be used?

**Comment by andreashaerter** [comment]
@lknite Since v6: no, it is not. Are you running from source (I do)? If so, you need:

* Recent code origin urls (e.g. `git remote set-url origin https://github.com/kaleidos-ventures/taiga-back.git` for backend)
* An additional Environment var, `DJANGO_SETTINGS_MODULE=settings.config` (e.g. in your systemd-service file)
* New config files for frontend and backend. Backend example:
   ```
   mv ~/taiga-back/settings/local.py ~/taiga-back/settings/local.py.v5.bak
   # create new config file based on the template
  cp ~/taiga-back/settings/config.py.prod.example ~/taiga-back/settings/config.py
  # adapt...
  ${EDITOR} ~/taiga-back/settings/config.py 
  ```
* Execute the migrations. Double check that `DJANGO_SETTINGS_MODULE=settings.config` is set (in doubt, run `export DJANGO_SETTINGS_MODULE=settings.config` and put that e.g. into the `.bashrc` of your dedicated taiga user)

Plus another few things... see https://docs.taiga.io/upgrades-5to6.html#taiga5src-to-taiga6src for details.

**Comment by lknite** [comment]
Worked on this more to load oidc values into config.py instead of local.py.

Dockerfile
```
# Start with latest official taiga-back image
FROM taigaio/taiga-back:6.4.2

# Install git, needed to install the oidc plugin
RUN apt update && \
  apt -y install vim git

# Install the oidc plugin
RUN \
  cd /tmp && \
  git clone https://github.com/kaleidos-ventures/taiga-contrib-oidc-auth.git && \
  cd /tmp/taiga-contrib-oidc-auth/back && \
  pip install -e .

#
COPY local.py /taiga-back/settings/local.py
COPY urls.py /taiga-back/settings/urls.py
# Insert contents from local.py into config.py after the line containing the string 'DEBUG = False'
RUN sed -i '/DEBUG = False/ r /taiga-back/settings/local.py' /taiga-back/settings/config.py
# Comment out ROOT_URLCONF in common.py in favor of the ROOT_URLCONF we inserted into config.py (should we be doing this?)
RUN sed -i 's/ROOT_URLCONF = "taiga.urls"/#ROOT_URLCONF = "taiga.urls"/g' /taiga-back/settings/common.py

RUN touch /tmp/debug.log
RUN chown taiga /tmp/debug.log
RUN chgrp taiga /tmp/debug.log

# ports and volumes
EXPOSE 8000/udp

#
ENTRYPOINT ["/taiga-back/docker/entrypoint.sh"]
```

**Comment by lknite** [comment]
@andreashaerter I'm using a really well built helm chart available here:  https://github.com/nemonik/taiga-helm .

Didn't mention kubernetes as I didn't want distract from the task.  I'm not working from code, working from prebuild taiga containers out at docker hub.

I'm working to follow the instructions available here:  https://github.com/kaleidos-ventures/taiga-contrib-oidc-auth

You can see in my previous posting how I'm trying to slightly modify the official taiga-back image to add the oidc module.  I can tell the local.py and urls.py are being processed as lines end up logged in /tmp/debug.log .

But when I click OPENID CONNECT to login it it still taking me to a 404 screen @ https://taiga.k-dev.harmony.net/oidc/authenticate/?next=%2Fdiscover.  Maybe the oidc path isn't being redirected to the extension?  Or maybe the extension isn't working?  Is there a way I could test this?  I did the gulp build on a different system rather than within the container image, if that matters.

Also, I don't fully know if I need to do something differently with ROOT_URLCONF since I'm importing the local.py into config.py now.

**Comment by lknite** [comment]
Also, I can confirm that the keycloak settings are correct at least on the keycloak side, as I used nearly identical settings to setup harbor oidc yesterday and am able to login to harbor using keycloak.

**Comment by lknite** [comment]
Was working to set the DJANGO_SETTINGS_MODULE variable then noticed it looks like its already being set:
```
$ k exec -it taiga-back-0 -- bash
root@taiga-back-0:/taiga-back# env | grep DJA
DJANGO_SETTINGS_MODULE=settings.config
root@taiga-back-0:/taiga-back#
```

**Comment by lknite** [comment]
Additional Test:

I removed the ROOT_URLCONF from my local.py, and did not comment out the existing ROOT_URLCONF.  Instead, I added to the taiga/urls.json like so:
```
##############################################
# Default
##############################################

urlpatterns = [
    url(r"^oidc/", include("mozilla_django_oidc.urls")),
    path('api/v1/', include(router.urls)),
    path('admin/', admin.site.urls),
```

still getting the same 404

Can someone confirm the taiga_contrib_oidc_auth plugin works with taiga 6?

**Comment by LecrisUT** [comment]
Thanks for reminding me about this. Previously I have used the other plugin which was rather painless to setup. In your case it's a bit tricky since you seem to be using a private dns, and network setup. It is rather difficult to gauge from where the issues come from. At the very least I think your issues with the hardcoded [callback url](https://github.com/kaleidos-ventures/taiga-contrib-oidc-auth/blob/3e07d17d871917d573afea084d707b69c3236462/front/coffee/oidc_auth.coffee#L68-L78) to Taiga being that of Taiga 5 instead of Taiga 6 (because the 404 you get is on Taiga page). It should be using a `redirect_uri` according to the standards in the first place. I would recommend switching to [robrotheram/taiga-contrib-openid-auth](https://github.com/robrotheram/taiga-contrib-openid-auth) and for Taiga team to fork that more complete one instead of this one.

Since then I have had studied more on the OAuth/OIDC that I could look into the implementation of the plugin and clean it up a bit. But due to time/work constraints I dunno when I'll be available to work on projects. At least I can leave you or anyone who wants to pick this up with some beginner tips for debugging that I picked up:
- Understanding the basics of [OAuth via `curl`](https://backstage.forgerock.com/knowledge/kb/article/a45882528).
- On firefox you can check the requests via `Web Developer Tools` (ctrl + shift + I) -> `Network`.

The few things that bother me with the current implementation/documentation:
- There are too many settings options. Ideally it should be built around the RFC and give example via a `keycloak` provider. All the specific options should be hidden and documented in a separate `advanced_settings.md` document. The settings should only be as:
```
INSTALLED_APPS += ["taiga_contrib_oidc_auth"]

AUTHENTICATION_BACKENDS = list(AUTHENTICATION_BACKENDS) + [
    "taiga_contrib_oidc_auth.oidc.TaigaOIDCAuthenticationBackend",
]

OIDC_URL = "https://keycloak.example.com/auth/realms/example/.well-known/openid-configuration"
OIDC_CLIENT_ID = "taiga"
OIDC_CLIENT_SECRET = "Secret"
```
- The settings is not designed for making it available to multiple sources (including pre-configured ones for popular vendors). It should have a object structure like [taiga's database settings](https://github.com/kaleidos-ventures/taiga-back/blob/e67b1b70851957a3e6e1b0e3ffbff2b4ddc1b25a/settings/common.py#L25-L33). Then the github/gitlab plugins should only be a pre-configured option in the settings.
- It should be added by default into taiga base (after it's polished as above).
- Unnecessary diagram and confusing choice of specific fedora OIDC naming.
- Probably there is a better OIDC dependency to introduce than `mozilla_django_oidc` that includes all presets. If not, manually making one shouldn't be difficult.
- Probably plenty more as we dig into the code itself.

**Comment by lknite** [comment]
Ok, I switched to  robrotheram/taiga-contrib-openid-auth and got everything working.

It's missing one thing that I can see, some way to add a certificate authority chain to the docker image.

I'll check with the maintainer to see if they have a way to get the chain added.
( see https://github.com/robrotheram/taiga-contrib-openid-auth/issues/34 )

And, to give some ideas, here's a screenshot from when setting up harbor to use keycloak:
![image](https://user-images.githubusercontent.com/92187614/147899466-61a9dc44-7834-45d9-b6c8-147676f66518.png)

The harbor setup worked first try.  Note the extra options to:
- Verify Certificate (useful when setting up to test if ssl certification validation is causing a problem, aka self-signed certificates)
- Automatic onboarding, which creates a user account immediately upon logging in and uses the username found by the values specified in 'username claim'.

One other thought, it would be nice to only allow people who only have valid accounts via oidc, and not allow them to create accounts otherwise.  Currently I believe you must set PUBLIC_REGISTER_ENABLED to True in order to use oidc.

**Comment by LecrisUT** [comment]
The CA issue is rather tricky because it uses the default python certificate chain. Indeed the best option would be to add an option to include a custom CA file and/or append it, but that would require quite a few changes to the backend if the python plugin even accepts it that is.

**Comment by lknite** [comment]
I'm checking with the plugin maintainer to see if he might have a way to make adding the ca chain in an easier way ( https://github.com/robrotheram/taiga-contrib-openid-auth/issues/34 ).  For now I'm accomplishing this using a method in kubernetes (see ticket 34) and going to also check with the helm chart maintainer ( https://github.com/nemonik/taiga-helm/issues/5 ) to see if they might be interested in adding some functionality.  In the end though I would think the taiga-back image itself would provide a way once oidc is integrated.

**Comment by LecrisUT** [comment]
This issue is completely confined to the openid plugin, particularly to the python backend. There could be great misunderstanding raising this issue on the taiga-helm side because it would imply adding these certificates to taiga front/backend. Thank you for raising all of these issues, but I would suggest to take it slow as most people are on holidays these days and devwork takes time. But please feel free to ping these issues again if you don't see any developments.

**Comment by lknite** [comment]
I understand.  I'm currently on vacation.  This is the sort of thing I do for fun.  We are all in this together.
