### ISSUE TITLE
unable to delete wiki

### ISSUE THREAD

**Issue by xfight0** [taigaio/taiga-back#687]
I can't delete any wiki, is it a bug in latest version?
error report:
```
api/v1/wiki/by_slug?project=2&slug=test-3 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by superalex** [comment]
Hello @xfight0 

I've just tested the stable version and it seems to be working ok. Taiga-front is doing DELETE requests to https://api.taiga.io/api/v1/wiki/WIKI_ID and the answers from the server are OK.

How could we reproduce the issue?

**Comment by xfight0** [comment]
Thank you for your reply.
I registered a account in taiga.io, creating a project, creating some wiki page, then I click delete icon in wiki page, nothing had happened. I found the errors in console:
```
https://api.taiga.io/api/v1/wiki/by_slug?project=119531&slug=home Failed to load resource: the server responded with a status of 404 (Not Found)
https://api.taiga.io/api/v1/wiki/by_slug?project=119531&slug=test Failed to load resource: the server responded with a status of 404 (Not Found)
```

Then, I installed a taiga by self host to test the issue, result is same.
I  would like  to give you my account and password to test the bug in private way.

**Comment by superalex** [comment]
Hello @xfight0 what button did you click to delete the icon wiki page?, the one where the "Remove this wiki page", after deleting the page that 404 request is normal because you are redirected to a home page that can not exist.

Regards,

**Comment by bameda** [comment]
We fix the delete button for wiki links.

**Comment by bameda** [comment]
![image](https://cloud.githubusercontent.com/assets/877218/14349757/93767964-fcc5-11e5-92b5-50316053a62e.png)

**Comment by xfight0** [comment]
@bameda I delete wiki from the sidebar icon, but get a 400 error in console, another issue: I can't change the wiki title. 
```
http://myhost/api/v1/wiki/by_slug?project=1&slug=qian-duan-gui-fan Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by bameda** [comment]
You don't delete a wiki page whit the icon in the sidebar. You delete a wiki link, but the wiki page is still created. To delete a wiki page you have to use the link under the attachment section.

Wiki page and wiki links are different items. You can have wiki pages without wiki links and wiki links without wiki pages.

If you are using your own instance of Taiga (and not taiga.io) can you update your taiga-front repository, clean the browser cache and try it again?
Can you explain the steps I have to follow to reproduce this bug?

Edit the name of a wiki page is an enhancement and not a bug, right  now the title of a wiki page is the identifier to know what is the url of the page. So if you change the title of a wiki page you broke all the links to this page (in other pages, stories, issues task or wiki links), so this behavior is intentional.

**Comment by xfight0** [comment]
@bameda Thank you, I updated taiga front to latest version.

**Comment by bameda** [comment]
You are welcome
