### ISSUE TITLE
Heroku support

### ISSUE THREAD

**Issue by michaelmior** [taigaio/taiga-back#81]
Would you consider adding support for easy deployment on Heroku? After looking at the project configuration, I suspect this would require fairly minimal changes. However, going this approach would be likely to do away with `settings.local` in favour of using environment variables for configuration.

**Comment by dheerajbhaskar** [comment]
Excuse me if this is overtly simple question. How do I deploy this to heroku, now that this issue is closed?

I'm a dev and just point me in the right direction and I'll figure out the rest. :)

**Comment by dheerajbhaskar** [comment]
Just found https://groups.google.com/forum/#!topic/taigaio/HtOqWA3SGic

I'm guessing this is not implemented yet. Any suggestions on how to go about this? 
Do I just deploy taiga on heroku like a standard django app?

Any thoughts, or guidance will be well appreciated.

**Comment by michaelmior** [comment]
@dheerajbhaskar There will be some code changes necessary since Heroku relies on environment variables for configuration.

**Comment by dheerajbhaskar** [comment]
Thanks for the quick reply Michael.

Where's this configuration being done now?
Do you think it's easy enough for me to change it to use environment vars?
As in is all the code in one place for me to refractor or is it at multiple
places with non-trivial changes?

On Tue 24 May, 2016, 6:23 PM Michael Mior, <notifications@github.com> wrote:

> @dheerajbhaskar <https://github.com/dheerajbhaskar> There will be some
> code changes necessary since Heroku relies on environment variables for
> configuration.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-back/issues/81#issuecomment-221259064>
>
-- 
--- Disclaimer --- The information in this mail is confidential and is
intended solely for addressee. Access to this mail by anyone else is
unauthorised. Copying or further distribution beyond the original recipient
may be unlawful. Any opinion expressed in this mail is that of sender and
does not necessarily reflect that of OSW Technologies Pvt Ltd.---

**Comment by michaelmior** [comment]
If you just want to get something working quickly, you could just pull the environment variables from Heroku and commit a configuration file with the changes. But it should be fairly easy to pull the changes from the environment as well. Either way, you just need to create a `local.py` based on [the example](https://github.com/taigaio/taiga-back/blob/master/settings/local.py.example).

**Comment by dheerajbhaskar** [comment]
This didn't make complete sense to me as I thought we needed to set the env
vars. Now you mention that I need to take (pull) the environment variables
and put them in local configuration file. My question would be where did
the env vars get set on heroku from? Are you assuming the buildpack would
set them at this point?

I'll take a look at the example and try this out first so that I can get
back to you with a proper question. Thanks for the help so far mate.

On Tue, May 24, 2016 at 10:02 PM Michael Mior <notifications@github.com>
wrote:

> If you just want to get something working quickly, you could just pull the
> environment variables from Heroku and commit a configuration file with the
> changes. But it should be fairly easy to pull the changes from the
> environment as well. Either way, you just need to create a local.py based
> on the example
> <https://github.com/taigaio/taiga-back/blob/master/settings/local.py.example>
> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-back/issues/81#issuecomment-221328786>
>
-- 
--- Disclaimer --- The information in this mail is confidential and is
intended solely for addressee. Access to this mail by anyone else is
unauthorised. Copying or further distribution beyond the original recipient
may be unlawful. Any opinion expressed in this mail is that of sender and
does not necessarily reflect that of OSW Technologies Pvt Ltd.---

**Comment by michaelmior** [comment]
Heroku sets environment variables such as `DATABASE_URL` based on what add-ons are configured in your application. I have a skeleton I use when I want to start a Django project on Heroku. As an example, you can see the [settings file](https://github.com/michaelmior/heroku-django-skeleton/blob/master/app/settings.py) I use in that project.
